<a href="https://colab.research.google.com/github/averma12/advent_of_code_23/blob/main/Advent_of_code_2023_day_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! pip install aocd

Requirement already satisfied: aocd in /usr/local/lib/python3.10/dist-packages (0.1)
Requirement already satisfied: advent-of-code-data in /usr/local/lib/python3.10/dist-packages (from aocd) (2.0.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from advent-of-code-data->aocd) (4.12.3)
Requirement already satisfied: pebble in /usr/local/lib/python3.10/dist-packages (from advent-of-code-data->aocd) (5.1.0)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.10/dist-packages (from advent-of-code-data->aocd) (2.2.3)
Requirement already satisfied: aocd-example-parser>=2023.2 in /usr/local/lib/python3.10/dist-packages (from advent-of-code-data->aocd) (2023.12.20)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->advent-of-code-data->aocd) (2.6)

In [2]:
from google.colab import userdata
AOC_SESSION = userdata.get('AOC_SESSION')

In [13]:
import os
os.environ['AOC_SESSION'] = AOC_SESSION

In [4]:
from aocd import get_data

data = get_data(day=5, year=2023)
print(data)

seeds: 222541566 218404460 670428364 432472902 2728902838 12147727 3962570697 52031641 2849288350 113747257 3648852659 73423293 4036058422 190602154 1931540843 584314999 3344622241 180428346 1301166628 310966761

seed-to-soil map:
357888202 777841571 45089383
1091769591 2222785614 212172358
747211456 668867483 108974088
635547523 229171508 111663933
1573402842 2067459960 102412403
4289698662 1148443045 5268634
2395735068 1322252554 161006801
0 205577967 4476015
57955189 635249899 15743396
402977585 0 26133741
464695488 412326242 24494890
2966156314 1301354919 3630744
42819069 472405294 15136120
3261136238 2193516168 29269446
2394617262 1304985663 1117806
3573311427 1725292988 265415981
3184385247 1990708969 76750991
36407558 487541414 6411511
178443976 26133741 179444226
4233901482 2444128986 55797180
2556741869 2169872363 23643805
429111326 436821132 35584162
4476015 622435882 12814017
2830010004 4158820986 136146310
1315195976 890236179 258206866
17290032 210053982 19117526
2969787058 3404926809 66954949
106953175 340835441 71490801
3307388168 3846327739 265923259
2580385674 3488864242 249624330
3036742007 1153711679 147643240
3290405684 3471881758 16982484
4187331494 4112250998 46569988
2378468177 1306103469 16149085
1308440551 2936378300 6755425
73698585 822930954 33254590
489190378 493952925 128482957
1675815245 1483259355 242033633
3849072207 2598119013 338259287
1917848878 2944307510 460619299
1303941949 885737577 4498602
3847898422 2943133725 1173785
617673335 650993295 17874188
993576744 2499926166 98192847
3838727408 2434957972 9171014
885737577 3738488572 107839167

soil-to-fertilizer map:
146677673 622659563 93167301
1157991666 1089969349 162939558
3393833863 2765693883 993201
1089969349 2528480087 47120899
1536155605 1455175707 97002831
77735382 829301434 68942291
519819619 496909514 125750049
1633158436 2638516375 127177508
2914682387 1777568650 8769904
1907493268 2936307342 209538906
1523198024 2370144872 12957581
398047045 375136940 121772574
3155987938 1552178538 225390112
2722437809 1786338554 7281125
2405956502 1793619679 316481307
4079025823 3374787635 121920527
1020706608 898243725 11125486
1320931224 1252908907 202266800
4200946350 4161901201 91091718
2872708010 4252992919 23854892
2896562902 4276847811 18119485
2923452291 2766687084 169620258
1760335944 2261396563 6024603
362307857 715826864 35739188
4292038068 2525550859 2929228
2345973561 2310161931 59982941
3426288597 3496708162 124839972
2768316300 2383102453 51488089
2729718934 2455491960 38597366
1137090248 2434590542 20901418
2819804389 2110100986 52903621
3394827064 2494089326 31461533
1809101312 2163004607 98391956
3551128569 3621548134 527897254
1766360547 2267421166 42740765
2117032174 3145846248 228941387
645569668 0 375136940
0 751566052 77735382
239844974 925431556 122462883
3093072549 2575600986 62915389
1031832094 909369211 16062345
3381378050 4149445388 12455813

fertilizer-to-water map:
1853863567 1354319094 57762399
1963297596 2892133710 74523026
351355449 2825239457 1556531
4263216859 3376413885 31750437
2555584073 3055976839 118124436
2730998967 1343408443 10910651
1638376751 979599391 153825342
978844708 811605824 82508702
1911625966 894114526 6715081
3367668240 3408164322 203176531
2729654714 3174101275 1344253
3200258520 795809557 15796267
1595497633 1782591008 42879118
2683440491 1412081493 46214223
1958950306 101242881 4347290
2831229721 242278649 124658639
1792202093 734148083 61661474
2741909618 2966656736 89320103
1918341047 3175445528 40609259
2955888360 1825470126 7069388
3594735667 3635231749 181844678
2673708509 412658344 9731982
2962957748 1832539514 237300772
530398473 105590171 136688478
1177133692 366937288 45721056
27883870 2489305043 153451249
352911980 2711533741 113705716
3570844771 3611340853 23890896
466617696 900829607 30422191
0 2461421173 27883870
3776580345 3360472089 15941796
4207783288 3817076427 55433571
2429401509 1249205015 60844842
181335119 2642756292 68777449
1061353410 1133424733 115780282
667086951 422390326 311757757
2490246351 2826795988 65337722
1222854748 931251798 48347593
1271202341 1458295716 324295292
3360472089 4287771145 7196151
497039887 1310049857 33358586
2037820622 2069840286 391580887
250112568 0 101242881
3792522141 3872509998 415261147

water-to-light map:
3392354816 2147745556 27501466
1878871951 1725889381 75406426
173441126 161378219 150090654
1018905669 635099142 165518615
4087062942 1662057640 30823678
353004829 1119237890 172394750
1845863888 1692881318 33008063
153206340 867143452 20234786
2604702405 4037570714 169107986
1617110925 3533554525 169325605
2559755690 1617110925 44946715
600097153 912061633 124651296
3946007322 3319554557 141055620
2465332301 3460610177 72944348
724748449 340941922 294157220
3044149982 2175247022 348204834
2773810391 2633005641 270339591
525399579 153206340 8171879
2139921020 3702880130 325411281
3419856282 1978376483 109941715
1954278377 2523451856 88074744
2538276649 2611526600 21479041
4117886620 1801295807 177080676
2051632424 4206678700 88288596
2042353121 4028291411 9279303
3529797997 2903345232 416209325
1786436530 2088318198 59427358
533571458 800617757 66525695
1184424284 1036712929 82524961
1266949245 887378238 24683395
323531780 311468873 29473049

light-to-temperature map:
2119656026 2694441768 51718564
582739623 515860164 331142829
3188466529 3433161801 686443431
1208858214 1852905471 223488011
2984018793 2746160332 20792175
114072893 923500840 335770555
1078092281 1568663312 55313164
1528379045 847002993 76497847
3159539374 3404234646 28927155
1604876892 44343574 471516590
3874909960 2119656026 229635679
913882452 1404453483 164209829
449843448 1720009296 132896175
3004810968 2539713362 154728406
1432346225 1623976476 96032820
2171374590 4119605232 175362064
2827425140 3247640993 156593653
1177749019 1259271395 31109195
2346736654 2766952507 480688486
1133405445 0 44343574
0 1290380590 114072893
4104545639 2349291705 190421657

temperature-to-humidity map:
4032879828 4294798436 168860
4033048688 927598400 261918608
0 101834652 315424112
3415479218 1417189709 517560635
3933039853 4175022329 99839975
2470365900 2513768139 498846371
2059440409 4274862304 19936132
2969212271 2295173893 218594246
315424112 417258764 36139086
351563198 0 101834652
927598400 1934750344 360423549
3187806517 1189517008 66595582
3254402099 1256112590 161077119
2079376541 3784032970 390989359
1288021949 3012614510 771418460

humidity-to-location map:
1627636687 2047220773 460084702
2744823277 560934787 184170906
3485120052 3437939311 342343442
3959782982 3213426504 221968093
1599327759 745105693 28308928
2311378749 773414621 172869650
4292422582 3435394597 2544714
4181751075 3780282753 110671507
2484248399 1371539463 260574878
944796451 1771589193 23241552
2985880462 4036578393 258388903
896379083 2507305475 48417368
2298631675 0 12747074
237282755 12747074 435619394
812377001 1310308951 61230512
1486759440 448366468 112568319
3827463494 2985880462 132319488
3389893498 3118199950 95226554
0 1073026196 237282755
672902149 1632114341 139474852
3244269365 3890954260 145624133
1103441152 2555722843 279347933
2181644796 1794830745 116986879
873607513 1050254626 22771570
968038003 1911817624 135403149
2087721389 2835070776 93923407
1382789085 946284271 103970355

In [5]:
len(data.splitlines())

242

In [6]:
sample = """seeds: 79 14 55 13

seed-to-soil map:
50 98 2
52 50 48

soil-to-fertilizer map:
0 15 37
37 52 2
39 0 15

fertilizer-to-water map:
49 53 8
0 11 42
42 0 7
57 7 4

water-to-light map:
88 18 7
18 25 70

light-to-temperature map:
45 77 23
81 45 19
68 64 13

temperature-to-humidity map:
0 69 1
1 0 69

humidity-to-location map:
60 56 37
56 93 4"""

In [7]:
import re
mappings = {}

lines = sample.splitlines()
pattern = r'(\w+)-to-(\w+) map:'

for i, line in enumerate(lines):
    match = re.search(pattern, line)
    if match:
        source = match.group(1)
        destination = match.group(2)

        # Find all number lines that follow until empty line or next mapping
        numbers = []
        current = i + 1
        while current < len(lines) and lines[current].strip():
            numbers.append(lines[current])
            current += 1

        # Store in dictionary with key like 'seed-to-soil'
        mapping_name = f'{source}-to-{destination}'
        mappings[mapping_name] = numbers

In [8]:
mappings

{'seed-to-soil': ['50 98 2', '52 50 48'],
 'soil-to-fertilizer': ['0 15 37', '37 52 2', '39 0 15'],
 'fertilizer-to-water': ['49 53 8', '0 11 42', '42 0 7', '57 7 4'],
 'water-to-light': ['88 18 7', '18 25 70'],
 'light-to-temperature': ['45 77 23', '81 45 19', '68 64 13'],
 'temperature-to-humidity': ['0 69 1', '1 0 69'],
 'humidity-to-location': ['60 56 37', '56 93 4']}

In [9]:
list(map(int, "50 98 2".split()))

[50, 98, 2]

In [10]:
# Example 1: Converting string numbers to integers
numbers = ["10", "20", "30"]
integers = list(map(int, numbers))
print(integers)  # Will print: [10, 20, 30]

[10, 20, 30]

In [11]:
# Example 2: Using a custom function
def double(x):
    return x * 2

numbers = [1, 2, 3, 4]
doubled = list(map(double, numbers))
print(doubled)  # Will print: [2, 4, 6, 8]

[2, 4, 6, 8]

In [12]:
def create_ranges_for_line(line):
    # Convert "50 98 2" into three integers [50, 98, 2]
    dest_start, source_start, length = map(int, line.split())

    # Create the ranges
    source_range = range(source_start, source_start + length)
    dest_range = range(dest_start, dest_start + length)

    return source_range, dest_range

# Let's test it with the first line from seed-to-soil
test_line = "50 98 2"
source_range, dest_range = create_ranges_for_line(test_line)

print(f"Source range: {list(source_range)}")  # Should print [98, 99]
print(f"Dest range: {list(dest_range)}")    # Should print [50, 51]

Source range: [98, 99]
Dest range: [50, 51]

In [14]:
for mapping in mappings:
    print(mappings[mapping])

['50 98 2', '52 50 48']
['0 15 37', '37 52 2', '39 0 15']
['49 53 8', '0 11 42', '42 0 7', '57 7 4']
['88 18 7', '18 25 70']
['45 77 23', '81 45 19', '68 64 13']
['0 69 1', '1 0 69']
['60 56 37', '56 93 4']

In [15]:
mapping = mappings['seed-to-soil']
source_range = []
dest_range = []
for line in mapping:
    source_range_line, dest_range_line = create_ranges_for_line(line)
    source_range.extend(list(source_range_line))
    dest_range.extend(list(dest_range_line))

In [16]:
source_range,dest_range

([98,
  99,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97],
 [50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99])

In [17]:
for mapping in mappings:
    lines = mappings[mapping]
    source_range = []
    dest_range = []
    for line in lines:
        source_range_line, dest_range_line = create_ranges_for_line(line)
        source_range.append(source_range_line)
        dest_range.append(dest_range_line)

In [18]:
all_mappings = {}
for mapping_name, mapping_lines in mappings.items():
    source_range = []
    dest_range = []
    for line in mapping_lines:
        source_range_line, dest_range_line = create_ranges_for_line(line)
        source_range.extend(list(source_range_line))
        dest_range.extend(list(dest_range_line))
    all_mappings[mapping_name] = (source_range, dest_range)

In [19]:
all_mappings["seed-to-soil"]

([98,
  99,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97],
 [50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99])

In [20]:
def create_mapping_ranges(mappings):
    all_mappings = {}
    for mapping_name, mapping_lines in mappings.items():
        source_range = []
        dest_range = []
        for line in mapping_lines:
            source_range_line, dest_range_line = create_ranges_for_line(line)
            source_range.extend(list(source_range_line))
            dest_range.extend(list(dest_range_line))
        all_mappings[mapping_name] = (source_range, dest_range)
    return all_mappings

In [21]:
all_mapping_ranges = create_mapping_ranges(mappings)

In [22]:
all_mapping_ranges["seed-to-soil"]

([98,
  99,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97],
 [50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99])

In [23]:
def get_column_names(mapping_name):
    # From "seed-to-soil" get ["seed", "soil"]
    pattern = r'(\w+)-to-(\w+)'
    match = re.search(pattern, mapping_name)
    return match.group(1), match.group(2)

In [24]:
import pandas as pd

In [25]:
def create_mapping_dataframes(all_mapping_ranges):
    dataframes = {}
    for mapping_name, (source_range, dest_range) in all_mapping_ranges.items():
        source_col, dest_col = get_column_names(mapping_name)
        df = pd.DataFrame({
            source_col: source_range,
            dest_col: dest_range
        }).reset_index(drop=True)  # Drop the index completely
        dataframes[mapping_name] = df
    return dataframes

In [26]:
all_dfs = create_mapping_dataframes(all_mapping_ranges)

In [27]:
all_dfs['seed-to-soil'].head()

   seed  soil
0    98    50
1    99    51
2    50    52
3    51    53
4    52    54

In [28]:
seed_to_soil = all_dfs['seed-to-soil']
soil_to_fert = all_dfs['soil-to-fertilizer']

# Merge on 'soil' column and fill NaN with -1
first_merge = pd.merge(seed_to_soil, soil_to_fert, on='soil', how='outer').fillna(-1)

In [51]:
first_merge.head()

   seed  soil  fertilizer
0  -1.0     0        39.0
1  -1.0     1        40.0
2  -1.0     2        41.0
3  -1.0     3        42.0
4  -1.0     4        43.0

In [29]:
# We already have first_merge with seed->soil->fertilizer

# Next merge with fertilizer-to-water
fert_to_water = all_dfs['fertilizer-to-water']
second_merge = pd.merge(first_merge, fert_to_water, on='fertilizer', how='outer').fillna(-1)

# Merge with water-to-light
water_to_light = all_dfs['water-to-light']
third_merge = pd.merge(second_merge, water_to_light, on='water', how='outer').fillna(-1)

# Merge with light-to-temperature
light_to_temp = all_dfs['light-to-temperature']
fourth_merge = pd.merge(third_merge, light_to_temp, on='light', how='outer').fillna(-1)

# Final merge with temperature-to-humidity
temp_to_humidity = all_dfs['temperature-to-humidity']
fifth_merge = pd.merge(fourth_merge, temp_to_humidity, on='temperature', how='outer').fillna(-1)

humdity_to_location = all_dfs['humidity-to-location']
final_merge = pd.merge(fifth_merge, humdity_to_location, on='humidity', how='outer').fillna(-1)

In [30]:
# First merge
first_merge = pd.merge(seed_to_soil, soil_to_fert, on='soil', how='outer').fillna(-1)

# Fix seed column: if seed is -1, use soil value
first_merge['seed'] = first_merge.apply(lambda row: row['soil'] if row['seed'] == -1 else row['seed'], axis=1)

# Second merge
second_merge = pd.merge(first_merge, fert_to_water, on='fertilizer', how='outer').fillna(-1)
# Fix previous columns similarly

# Fix in order from left to right:
second_merge['fertilizer'] = second_merge.apply(lambda row: row['soil'] if row['fertilizer'] == -1 else row['fertilizer'], axis=1)
second_merge['water'] = second_merge.apply(lambda row: row['fertilizer'] if row['water'] == -1 else row['water'], axis=1)
second_merge['soil'] = second_merge.apply(lambda row: row['fertilizer'] if row['soil'] == -1 else row['soil'], axis=1)
second_merge['seed'] = second_merge.apply(lambda row: row['soil'] if row['seed'] == -1 else row['seed'], axis=1)

In [31]:
second_merge

     seed  soil  fertilizer  water
0    52.0  54.0        54.0   54.0
1    53.0  55.0        55.0   55.0
2    54.0  56.0        56.0   56.0
3    55.0  57.0        57.0   57.0
4    56.0  58.0        58.0   58.0
..    ...   ...         ...    ...
102  56.0  56.0        56.0   52.0
103  57.0  57.0        57.0   53.0
104  58.0  58.0        58.0   54.0
105  59.0  59.0        59.0   55.0
106  60.0  60.0        60.0   56.0

[107 rows x 4 columns]

In [32]:
# Third merge
third_merge = pd.merge(second_merge, water_to_light, on='water', how='outer').fillna(-1)

# Fix any -1s in the new columns from left to right
third_merge['light'] = third_merge.apply(lambda row: row['water'] if row['light'] == -1 else row['light'], axis=1)

In [33]:
third_merge

     seed  soil  fertilizer  water  light
0    26.0  26.0        11.0    0.0    0.0
1    27.0  27.0        12.0    1.0    1.0
2    28.0  28.0        13.0    2.0    2.0
3    29.0  29.0        14.0    3.0    3.0
4    30.0  30.0        15.0    4.0    4.0
..    ...   ...         ...    ...    ...
102  93.0  95.0        95.0   95.0   95.0
103  94.0  96.0        96.0   96.0   96.0
104  95.0  97.0        97.0   97.0   97.0
105  96.0  98.0        98.0   98.0   98.0
106  97.0  99.0        99.0   99.0   99.0

[107 rows x 5 columns]

In [34]:
# Fourth merge (light-to-temperature)
fourth_merge = pd.merge(third_merge, light_to_temp, on='light', how='outer').fillna(-1)

# Fix -1s
fourth_merge['temperature'] = fourth_merge.apply(lambda row: row['light'] if row['temperature'] == -1 else row['temperature'], axis=1)

In [35]:
# Final merge (temperature-to-humidity)
final_merge = pd.merge(fourth_merge, temp_to_humidity, on='temperature', how='outer').fillna(-1)

# Fix -1s
final_merge['humidity'] = final_merge.apply(lambda row: row['temperature'] if row['humidity'] == -1 else row['humidity'], axis=1)

In [36]:
humidity_to_loc = all_dfs['humidity-to-location']
final_final_merge = pd.merge(final_merge, humidity_to_loc, on='humidity', how='outer').fillna(-1)

# Fix -1s in location column
final_final_merge['location'] = final_final_merge.apply(lambda row: row['humidity'] if row['location'] == -1 else row['location'], axis=1)

In [37]:
final_final_merge

     seed  soil  fertilizer  water  light  temperature  humidity  location
0    70.0  72.0        72.0   72.0   65.0         69.0       0.0       0.0
1    26.0  26.0        11.0    0.0    0.0          0.0       1.0       1.0
2    27.0  27.0        12.0    1.0    1.0          1.0       2.0       2.0
3    28.0  28.0        13.0    2.0    2.0          2.0       3.0       3.0
4    29.0  29.0        14.0    3.0    3.0          3.0       4.0       4.0
..    ...   ...         ...    ...    ...          ...       ...       ...
102  64.0  66.0        66.0   66.0   59.0         95.0      95.0      58.0
103  65.0  67.0        67.0   67.0   60.0         96.0      96.0      59.0
104  66.0  68.0        68.0   68.0   61.0         97.0      97.0      97.0
105  67.0  69.0        69.0   69.0   62.0         98.0      98.0      98.0
106  68.0  70.0        70.0   70.0   63.0         99.0      99.0      99.0

[107 rows x 8 columns]

In [38]:
# To see how many -1s are in each column
negative_counts = (final_final_merge == -1).sum()

In [39]:
negative_counts

seed           0
soil           0
fertilizer     0
water          0
light          0
temperature    0
humidity       0
location       0
dtype: int64

In [40]:
seed_values = [79, 14, 55, 13]

# Filter final DataFrame for these seed values
locations = final_final_merge[final_final_merge['seed'].isin(seed_values)][['seed', 'location']]

# Sort by seed value for clarity
locations = locations.sort_values('seed')
print("Location values for seeds:", seed_values)
print(locations)

Location values for seeds: [79, 14, 55, 13]
    seed  location
35  13.0      35.0
43  14.0      43.0
45  55.0      45.0
89  55.0      90.0
78  79.0      82.0

In [43]:
locations.min()["location"]

35.0

In [41]:
min_location = final_final_merge[final_final_merge['seed'].isin(seed_values)]['location'].min()

print(f"Minimum location value: {min_location}")

Minimum location value: 35.0

In [44]:
def process_mapping_chain(all_dfs, seed_values=None):
    """
    Process the complete chain of mappings from seed to location.
    """
    seed_to_soil = all_dfs['seed-to-soil']
    soil_to_fert = all_dfs['soil-to-fertilizer']
    # First merge
    first_merge = pd.merge(seed_to_soil, soil_to_fert, on='soil', how='outer').fillna(-1)

    # Fix seed column: if seed is -1, use soil value
    first_merge['seed'] = first_merge.apply(lambda row: row['soil'] if row['seed'] == -1 else row['seed'], axis=1)

    # Second merge
    second_merge = pd.merge(first_merge, fert_to_water, on='fertilizer', how='outer').fillna(-1)
    # Fix previous columns similarly

    # Fix in order from left to right:
    second_merge['fertilizer'] = second_merge.apply(lambda row: row['soil'] if row['fertilizer'] == -1 else row['fertilizer'], axis=1)
    second_merge['water'] = second_merge.apply(lambda row: row['fertilizer'] if row['water'] == -1 else row['water'], axis=1)
    second_merge['soil'] = second_merge.apply(lambda row: row['fertilizer'] if row['soil'] == -1 else row['soil'], axis=1)
    second_merge['seed'] = second_merge.apply(lambda row: row['soil'] if row['seed'] == -1 else row['seed'], axis=1)
    # Third merge
    water_to_light = all_dfs['water-to-light']
    third_merge = pd.merge(second_merge, water_to_light, on='water', how='outer').fillna(-1)

    # Fix any -1s in the new columns from left to right
    third_merge['light'] = third_merge.apply(lambda row: row['water'] if row['light'] == -1 else row['light'], axis=1)
    # Fourth merge
    light_to_temp = all_dfs['light-to-temperature']
    fourth_merge = pd.merge(third_merge, light_to_temp, on='light', how='outer').fillna(-1)
    fourth_merge['temperature'] = fourth_merge.apply(lambda row: row['light'] if row['temperature'] == -1 else row['temperature'], axis=1)

    # Fifth merge
    temp_to_humidity = all_dfs['temperature-to-humidity']
    fifth_merge = pd.merge(fourth_merge, temp_to_humidity, on='temperature', how='outer').fillna(-1)
    fifth_merge['humidity'] = fifth_merge.apply(lambda row: row['temperature'] if row['humidity'] == -1 else row['humidity'], axis=1)

    #Final merge
    humidity_to_location = all_dfs['humidity-to-location']
    final_merge = pd.merge(fifth_merge, humidity_to_location, on='humidity', how='outer').fillna(-1)
    final_merge['location'] = final_merge.apply(lambda row: row['humidity'] if row['location'] == -1 else row['location'], axis=1)

    return final_merge

# Part 1

In [45]:
data.splitlines()

['seeds: 222541566 218404460 670428364 432472902 2728902838 12147727 3962570697 52031641 2849288350 113747257 3648852659 73423293 4036058422 190602154 1931540843 584314999 3344622241 180428346 1301166628 310966761',
 '',
 'seed-to-soil map:',
 '357888202 777841571 45089383',
 '1091769591 2222785614 212172358',
 '747211456 668867483 108974088',
 '635547523 229171508 111663933',
 '1573402842 2067459960 102412403',
 '4289698662 1148443045 5268634',
 '2395735068 1322252554 161006801',
 '0 205577967 4476015',
 '57955189 635249899 15743396',
 '402977585 0 26133741',
 '464695488 412326242 24494890',
 '2966156314 1301354919 3630744',
 '42819069 472405294 15136120',
 '3261136238 2193516168 29269446',
 '2394617262 1304985663 1117806',
 '3573311427 1725292988 265415981',
 '3184385247 1990708969 76750991',
 '36407558 487541414 6411511',
 '178443976 26133741 179444226',
 '4233901482 2444128986 55797180',
 '2556741869 2169872363 23643805',
 '429111326 436821132 35584162',
 '4476015 622435882 12814017',
 '2830010004 4158820986 136146310',
 '1315195976 890236179 258206866',
 '17290032 210053982 19117526',
 '2969787058 3404926809 66954949',
 '106953175 340835441 71490801',
 '3307388168 3846327739 265923259',
 '2580385674 3488864242 249624330',
 '3036742007 1153711679 147643240',
 '3290405684 3471881758 16982484',
 '4187331494 4112250998 46569988',
 '2378468177 1306103469 16149085',
 '1308440551 2936378300 6755425',
 '73698585 822930954 33254590',
 '489190378 493952925 128482957',
 '1675815245 1483259355 242033633',
 '3849072207 2598119013 338259287',
 '1917848878 2944307510 460619299',
 '1303941949 885737577 4498602',
 '3847898422 2943133725 1173785',
 '617673335 650993295 17874188',
 '993576744 2499926166 98192847',
 '3838727408 2434957972 9171014',
 '885737577 3738488572 107839167',
 '',
 'soil-to-fertilizer map:',
 '146677673 622659563 93167301',
 '1157991666 1089969349 162939558',
 '3393833863 2765693883 993201',
 '1089969349 2528480087 47120899',
 '1536155605 1455175707 97002831',
 '77735382 829301434 68942291',
 '519819619 496909514 125750049',
 '1633158436 2638516375 127177508',
 '2914682387 1777568650 8769904',
 '1907493268 2936307342 209538906',
 '1523198024 2370144872 12957581',
 '398047045 375136940 121772574',
 '3155987938 1552178538 225390112',
 '2722437809 1786338554 7281125',
 '2405956502 1793619679 316481307',
 '4079025823 3374787635 121920527',
 '1020706608 898243725 11125486',
 '1320931224 1252908907 202266800',
 '4200946350 4161901201 91091718',
 '2872708010 4252992919 23854892',
 '2896562902 4276847811 18119485',
 '2923452291 2766687084 169620258',
 '1760335944 2261396563 6024603',
 '362307857 715826864 35739188',
 '4292038068 2525550859 2929228',
 '2345973561 2310161931 59982941',
 '3426288597 3496708162 124839972',
 '2768316300 2383102453 51488089',
 '2729718934 2455491960 38597366',
 '1137090248 2434590542 20901418',
 '2819804389 2110100986 52903621',
 '3394827064 2494089326 31461533',
 '1809101312 2163004607 98391956',
 '3551128569 3621548134 527897254',
 '1766360547 2267421166 42740765',
 '2117032174 3145846248 228941387',
 '645569668 0 375136940',
 '0 751566052 77735382',
 '239844974 925431556 122462883',
 '3093072549 2575600986 62915389',
 '1031832094 909369211 16062345',
 '3381378050 4149445388 12455813',
 '',
 'fertilizer-to-water map:',
 '1853863567 1354319094 57762399',
 '1963297596 2892133710 74523026',
 '351355449 2825239457 1556531',
 '4263216859 3376413885 31750437',
 '2555584073 3055976839 118124436',
 '2730998967 1343408443 10910651',
 '1638376751 979599391 153825342',
 '978844708 811605824 82508702',
 '1911625966 894114526 6715081',
 '3367668240 3408164322 203176531',
 '2729654714 3174101275 1344253',
 '3200258520 795809557 15796267',
 '1595497633 1782591008 42879118',
 '2683440491 1412081493 46214223',
 '1958950306 101242881 4347290',
 '2831229721 242278649 124658639',
 '1792202093 734148083 61661474',
 '2741909618 2966656736 89320103',
 '1918341047 3175445528 40609259',
 '2955888360 1825470126 7069388',
 '3594735667 3635231749 181844678',
 '2673708509 412658344 9731982',
 '2962957748 1832539514 237300772',
 '530398473 105590171 136688478',
 '1177133692 366937288 45721056',
 '27883870 2489305043 153451249',
 '352911980 2711533741 113705716',
 '3570844771 3611340853 23890896',
 '466617696 900829607 30422191',
 '0 2461421173 27883870',
 '3776580345 3360472089 15941796',
 '4207783288 3817076427 55433571',
 '2429401509 1249205015 60844842',
 '181335119 2642756292 68777449',
 '1061353410 1133424733 115780282',
 '667086951 422390326 311757757',
 '2490246351 2826795988 65337722',
 '1222854748 931251798 48347593',
 '1271202341 1458295716 324295292',
 '3360472089 4287771145 7196151',
 '497039887 1310049857 33358586',
 '2037820622 2069840286 391580887',
 '250112568 0 101242881',
 '3792522141 3872509998 415261147',
 '',
 'water-to-light map:',
 '3392354816 2147745556 27501466',
 '1878871951 1725889381 75406426',
 '173441126 161378219 150090654',
 '1018905669 635099142 165518615',
 '4087062942 1662057640 30823678',
 '353004829 1119237890 172394750',
 '1845863888 1692881318 33008063',
 '153206340 867143452 20234786',
 '2604702405 4037570714 169107986',
 '1617110925 3533554525 169325605',
 '2559755690 1617110925 44946715',
 '600097153 912061633 124651296',
 '3946007322 3319554557 141055620',
 '2465332301 3460610177 72944348',
 '724748449 340941922 294157220',
 '3044149982 2175247022 348204834',
 '2773810391 2633005641 270339591',
 '525399579 153206340 8171879',
 '2139921020 3702880130 325411281',
 '3419856282 1978376483 109941715',
 '1954278377 2523451856 88074744',
 '2538276649 2611526600 21479041',
 '4117886620 1801295807 177080676',
 '2051632424 4206678700 88288596',
 '2042353121 4028291411 9279303',
 '3529797997 2903345232 416209325',
 '1786436530 2088318198 59427358',
 '533571458 800617757 66525695',
 '1184424284 1036712929 82524961',
 '1266949245 887378238 24683395',
 '323531780 311468873 29473049',
 '',
 'light-to-temperature map:',
 '2119656026 2694441768 51718564',
 '582739623 515860164 331142829',
 '3188466529 3433161801 686443431',
 '1208858214 1852905471 223488011',
 '2984018793 2746160332 20792175',
 '114072893 923500840 335770555',
 '1078092281 1568663312 55313164',
 '1528379045 847002993 76497847',
 '3159539374 3404234646 28927155',
 '1604876892 44343574 471516590',
 '3874909960 2119656026 229635679',
 '913882452 1404453483 164209829',
 '449843448 1720009296 132896175',
 '3004810968 2539713362 154728406',
 '1432346225 1623976476 96032820',
 '2171374590 4119605232 175362064',
 '2827425140 3247640993 156593653',
 '1177749019 1259271395 31109195',
 '2346736654 2766952507 480688486',
 '1133405445 0 44343574',
 '0 1290380590 114072893',
 '4104545639 2349291705 190421657',
 '',
 'temperature-to-humidity map:',
 '4032879828 4294798436 168860',
 '4033048688 927598400 261918608',
 '0 101834652 315424112',
 '3415479218 1417189709 517560635',
 '3933039853 4175022329 99839975',
 '2470365900 2513768139 498846371',
 '2059440409 4274862304 19936132',
 '2969212271 2295173893 218594246',
 '315424112 417258764 36139086',
 '351563198 0 101834652',
 '927598400 1934750344 360423549',
 '3187806517 1189517008 66595582',
 '3254402099 1256112590 161077119',
 '2079376541 3784032970 390989359',
 '1288021949 3012614510 771418460',
 '',
 'humidity-to-location map:',
 '1627636687 2047220773 460084702',
 '2744823277 560934787 184170906',
 '3485120052 3437939311 342343442',
 '3959782982 3213426504 221968093',
 '1599327759 745105693 28308928',
 '2311378749 773414621 172869650',
 '4292422582 3435394597 2544714',
 '4181751075 3780282753 110671507',
 '2484248399 1371539463 260574878',
 '944796451 1771589193 23241552',
 '2985880462 4036578393 258388903',
 '896379083 2507305475 48417368',
 '2298631675 0 12747074',
 '237282755 12747074 435619394',
 '812377001 1310308951 61230512',
 '1486759440 448366468 112568319',
 '3827463494 2985880462 132319488',
 '3389893498 3118199950 95226554',
 '0 1073026196 237282755',
 '672902149 1632114341 139474852',
 '3244269365 3890954260 145624133',
 '1103441152 2555722843 279347933',
 '2181644796 1794830745 116986879',
 '873607513 1050254626 22771570',
 '968038003 1911817624 135403149',
 '2087721389 2835070776 93923407',
 '1382789085 946284271 103970355']

In [62]:
import re
mappings = {}

lines = data.splitlines()
pattern = r'(\w+)-to-(\w+) map:'

for i, line in enumerate(lines):
    match = re.search(pattern, line)
    if match:
        source = match.group(1)
        destination = match.group(2)

        # Find all number lines that follow until empty line or next mapping
        numbers = []
        current = i + 1
        while current < len(lines) and lines[current].strip():
            numbers.append(lines[current])
            current += 1

        # Store in dictionary with key like 'seed-to-soil'
        mapping_name = f'{source}-to-{destination}'
        mappings[mapping_name] = numbers

In [63]:
mappings["seed-to-soil"]

['357888202 777841571 45089383',
 '1091769591 2222785614 212172358',
 '747211456 668867483 108974088',
 '635547523 229171508 111663933',
 '1573402842 2067459960 102412403',
 '4289698662 1148443045 5268634',
 '2395735068 1322252554 161006801',
 '0 205577967 4476015',
 '57955189 635249899 15743396',
 '402977585 0 26133741',
 '464695488 412326242 24494890',
 '2966156314 1301354919 3630744',
 '42819069 472405294 15136120',
 '3261136238 2193516168 29269446',
 '2394617262 1304985663 1117806',
 '3573311427 1725292988 265415981',
 '3184385247 1990708969 76750991',
 '36407558 487541414 6411511',
 '178443976 26133741 179444226',
 '4233901482 2444128986 55797180',
 '2556741869 2169872363 23643805',
 '429111326 436821132 35584162',
 '4476015 622435882 12814017',
 '2830010004 4158820986 136146310',
 '1315195976 890236179 258206866',
 '17290032 210053982 19117526',
 '2969787058 3404926809 66954949',
 '106953175 340835441 71490801',
 '3307388168 3846327739 265923259',
 '2580385674 3488864242 249624330',
 '3036742007 1153711679 147643240',
 '3290405684 3471881758 16982484',
 '4187331494 4112250998 46569988',
 '2378468177 1306103469 16149085',
 '1308440551 2936378300 6755425',
 '73698585 822930954 33254590',
 '489190378 493952925 128482957',
 '1675815245 1483259355 242033633',
 '3849072207 2598119013 338259287',
 '1917848878 2944307510 460619299',
 '1303941949 885737577 4498602',
 '3847898422 2943133725 1173785',
 '617673335 650993295 17874188',
 '993576744 2499926166 98192847',
 '3838727408 2434957972 9171014',
 '885737577 3738488572 107839167']

In [47]:
#all_mapping_ranges = create_mapping_ranges(mappings)

In [46]:
def find_mapping(number, mapping_rules):
    for line in mapping_rules:
        dest_start, source_start, length = map(int, line.split())
        if source_start <= number < source_start + length:
            offset = number - source_start
            return dest_start + offset
    return number

In [48]:
seed = int("222541566")
soil = find_mapping(seed, mappings["seed-to-soil"])

In [49]:
soil

222541566

In [50]:
def get_all_mappings(number, mappings):
    """
    Get all mappings for a number through the complete chain.

    Args:
        number: Starting number (seed)
        mappings: Dictionary containing all mapping rules

    Returns:
        Dictionary with all mapped values
    """
    result = {'seed': number}

    # Order of mappings
    mapping_chain = [
        'seed-to-soil',
        'soil-to-fertilizer',
        'fertilizer-to-water',
        'water-to-light',
        'light-to-temperature',
        'temperature-to-humidity',
        'humidity-to-location'
    ]

    current = number
    for mapping_name in mapping_chain:
        current = find_mapping(current, mappings[mapping_name])
        # Get the destination name from the mapping (e.g., 'soil' from 'seed-to-soil')
        dest_name = mapping_name.split('-to-')[1]
        result[dest_name] = current

    return result

# Usage example:
# seed = 79
# mapped_values = get_all_mappings(seed, mappings)
# This would return something like:
# {
#     'seed': 79,
#     'soil': 81,
#     'fertilizer': 81,
#     'water': 81,
#     'light': 74,
#     'temperature': 78,
#     'humidity': 78,
#     'location': 82
# }

In [57]:
get_all_mappings(12147727, mappings)

{'seed': 12147727,
 'soil': 12147727,
 'fertilizer': 12147727,
 'water': 12147727,
 'light': 12147727,
 'temperature': 12147727,
 'humidity': 12147727,
 'location': 12147727}

In [54]:
seed = "222541566 218404460 670428364 432472902 2728902838 12147727 3962570697 52031641 2849288350 113747257 3648852659 73423293 4036058422 190602154 1931540843 584314999 3344622241 180428346 1301166628 310966761"
seeds = list(map(int, seed.split()))

In [56]:
min(seeds)

12147727

In [66]:
def find_mapping(number, mapping_rules):
    """
    Find mapping for a number based on rules.
    Each rule is a string like '50 98 2' meaning numbers 98-99 map to 50-51
    """
    for line in mapping_rules:
        dest_start, source_start, length = map(int, line.split())
        if source_start <= number < source_start + length:
            offset = number - source_start
            return dest_start + offset
    return number

def get_all_mappings(seed, mappings):
    """
    Get all mappings for a seed through the entire chain.
    """
    result = {'seed': seed}
    mapping_chain = [
        'seed-to-soil',
        'soil-to-fertilizer',
        'fertilizer-to-water',
        'water-to-light',
        'light-to-temperature',
        'temperature-to-humidity',
        'humidity-to-location'
    ]

    current = seed
    for mapping_name in mapping_chain:
        current = find_mapping(current, mappings[mapping_name])
        dest_name = mapping_name.split('-to-')[1]
        result[dest_name] = current

    return result

# Let's test with the first seed number
test_seed = 222541566
result = get_all_mappings(test_seed, mappings)
print(result)

{'seed': 222541566, 'soil': 29777616, 'fertilizer': 675347284, 'water': 920043909, 'light': 608079429, 'temperature': 674958888, 'humidity': 674958888, 'location': 2858847378}

In [67]:
all_locations = []
for seed in seeds:
    result = get_all_mappings(seed, mappings)
    all_locations.append(result['location'])

In [68]:
min(all_locations)

379811651

In [65]:
find_mapping(222541566, mappings["seed-to-soil"])

Checking number: 222541566
Rule: dest=357888202, source=777841571, len=45089383
Checking if 222541566 is between 777841571 and 822930954
Rule: dest=1091769591, source=2222785614, len=212172358
Checking if 222541566 is between 2222785614 and 2434957972
Rule: dest=747211456, source=668867483, len=108974088
Checking if 222541566 is between 668867483 and 777841571
Rule: dest=635547523, source=229171508, len=111663933
Checking if 222541566 is between 229171508 and 340835441
Rule: dest=1573402842, source=2067459960, len=102412403
Checking if 222541566 is between 2067459960 and 2169872363
Rule: dest=4289698662, source=1148443045, len=5268634
Checking if 222541566 is between 1148443045 and 1153711679
Rule: dest=2395735068, source=1322252554, len=161006801
Checking if 222541566 is between 1322252554 and 1483259355
Rule: dest=0, source=205577967, len=4476015
Checking if 222541566 is between 205577967 and 210053982
Rule: dest=57955189, source=635249899, len=15743396
Checking if 222541566 is between 635249899 and 650993295
Rule: dest=402977585, source=0, len=26133741
Checking if 222541566 is between 0 and 26133741
Rule: dest=464695488, source=412326242, len=24494890
Checking if 222541566 is between 412326242 and 436821132
Rule: dest=2966156314, source=1301354919, len=3630744
Checking if 222541566 is between 1301354919 and 1304985663
Rule: dest=42819069, source=472405294, len=15136120
Checking if 222541566 is between 472405294 and 487541414
Rule: dest=3261136238, source=2193516168, len=29269446
Checking if 222541566 is between 2193516168 and 2222785614
Rule: dest=2394617262, source=1304985663, len=1117806
Checking if 222541566 is between 1304985663 and 1306103469
Rule: dest=3573311427, source=1725292988, len=265415981
Checking if 222541566 is between 1725292988 and 1990708969
Rule: dest=3184385247, source=1990708969, len=76750991
Checking if 222541566 is between 1990708969 and 2067459960
Rule: dest=36407558, source=487541414, len=6411511
Checking if 222541566 is between 487541414 and 493952925
Rule: dest=178443976, source=26133741, len=179444226
Checking if 222541566 is between 26133741 and 205577967
Rule: dest=4233901482, source=2444128986, len=55797180
Checking if 222541566 is between 2444128986 and 2499926166
Rule: dest=2556741869, source=2169872363, len=23643805
Checking if 222541566 is between 2169872363 and 2193516168
Rule: dest=429111326, source=436821132, len=35584162
Checking if 222541566 is between 436821132 and 472405294
Rule: dest=4476015, source=622435882, len=12814017
Checking if 222541566 is between 622435882 and 635249899
Rule: dest=2830010004, source=4158820986, len=136146310
Checking if 222541566 is between 4158820986 and 4294967296
Rule: dest=1315195976, source=890236179, len=258206866
Checking if 222541566 is between 890236179 and 1148443045
Rule: dest=17290032, source=210053982, len=19117526
Checking if 222541566 is between 210053982 and 229171508
Found match! Offset=12487584, Result=29777616

29777616

In [64]:
def find_mapping(number, mapping_rules):
    print(f"Checking number: {number}")  # Debug print
    for line in mapping_rules:
        dest_start, source_start, length = map(int, line.split())
        print(f"Rule: dest={dest_start}, source={source_start}, len={length}")  # Debug print
        print(f"Checking if {number} is between {source_start} and {source_start + length}")
        if source_start <= number < source_start + length:
            offset = number - source_start
            result = dest_start + offset
            print(f"Found match! Offset={offset}, Result={result}")  # Debug print
            return dest_start + offset
    print("No match found, returning original number")  # Debug print
    return number

# Test with first seed and just seed-to-soil mapping
test_seed = 222541566
soil = find_mapping(test_seed, mappings['seed-to-soil'])
print(f"Final result: {soil}")

Checking number: 222541566
Rule: dest=357888202, source=777841571, len=45089383
Checking if 222541566 is between 777841571 and 822930954
Rule: dest=1091769591, source=2222785614, len=212172358
Checking if 222541566 is between 2222785614 and 2434957972
Rule: dest=747211456, source=668867483, len=108974088
Checking if 222541566 is between 668867483 and 777841571
Rule: dest=635547523, source=229171508, len=111663933
Checking if 222541566 is between 229171508 and 340835441
Rule: dest=1573402842, source=2067459960, len=102412403
Checking if 222541566 is between 2067459960 and 2169872363
Rule: dest=4289698662, source=1148443045, len=5268634
Checking if 222541566 is between 1148443045 and 1153711679
Rule: dest=2395735068, source=1322252554, len=161006801
Checking if 222541566 is between 1322252554 and 1483259355
Rule: dest=0, source=205577967, len=4476015
Checking if 222541566 is between 205577967 and 210053982
Rule: dest=57955189, source=635249899, len=15743396
Checking if 222541566 is between 635249899 and 650993295
Rule: dest=402977585, source=0, len=26133741
Checking if 222541566 is between 0 and 26133741
Rule: dest=464695488, source=412326242, len=24494890
Checking if 222541566 is between 412326242 and 436821132
Rule: dest=2966156314, source=1301354919, len=3630744
Checking if 222541566 is between 1301354919 and 1304985663
Rule: dest=42819069, source=472405294, len=15136120
Checking if 222541566 is between 472405294 and 487541414
Rule: dest=3261136238, source=2193516168, len=29269446
Checking if 222541566 is between 2193516168 and 2222785614
Rule: dest=2394617262, source=1304985663, len=1117806
Checking if 222541566 is between 1304985663 and 1306103469
Rule: dest=3573311427, source=1725292988, len=265415981
Checking if 222541566 is between 1725292988 and 1990708969
Rule: dest=3184385247, source=1990708969, len=76750991
Checking if 222541566 is between 1990708969 and 2067459960
Rule: dest=36407558, source=487541414, len=6411511
Checking if 222541566 is between 487541414 and 493952925
Rule: dest=178443976, source=26133741, len=179444226
Checking if 222541566 is between 26133741 and 205577967
Rule: dest=4233901482, source=2444128986, len=55797180
Checking if 222541566 is between 2444128986 and 2499926166
Rule: dest=2556741869, source=2169872363, len=23643805
Checking if 222541566 is between 2169872363 and 2193516168
Rule: dest=429111326, source=436821132, len=35584162
Checking if 222541566 is between 436821132 and 472405294
Rule: dest=4476015, source=622435882, len=12814017
Checking if 222541566 is between 622435882 and 635249899
Rule: dest=2830010004, source=4158820986, len=136146310
Checking if 222541566 is between 4158820986 and 4294967296
Rule: dest=1315195976, source=890236179, len=258206866
Checking if 222541566 is between 890236179 and 1148443045
Rule: dest=17290032, source=210053982, len=19117526
Checking if 222541566 is between 210053982 and 229171508
Found match! Offset=12487584, Result=29777616
Final result: 29777616